# Run pre-commit autoupdate every day at midnight
# and create a pull request if any changes
name: Pre-commit auto-update

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit autoupdate
        run: pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.5.0
        with:
          # CI won't be running on pull requests by default
          token: ${{ secrets.GITHUB_TOKEN }}
          # Change to a personal access token with the 'repo' scope
          # and save it as CPR_GITHUB_TOKEN to get it to work
          # https://github.com/settings/tokens/new?scopes=repo
          # token: ${{ secrets.CPR_GITHUB_TOKEN }}
          branch: update/pre-commit-autoupdate
          title: Auto-update pre-commit hooks
          commit-message: Auto-update pre-commit hooks
          body: Update versions of tools in pre-commit configs to latest version
          labels: dependencies
